// Code generated by hertz generator.

package product

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchproductlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
