
services:
  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo_proto
  # consul 无法访问宿主机端口
  # consul:
  #   image: 'hashicorp/consul'
  #   ports:
  #     - 8500:8500
  #     - 8600:8600/udp 